Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-10, with the labels that each got.

#146 BetterPartyFinder
  stable/BetterPartyFinder/manifest.toml
Labels: size-small

#145 NoTankYou CN
  stable/NoTankYou/manifest.toml
Labels: size-small

#144 DailyDuty CN
  stable/DailyDuty/manifest.toml
Labels: size-mid

#142 [Testing] Currency Tracker 1.2.3.3
  testing/live/CurrencyTracker/manifest.toml
Labels: size-large

#147 OBSPlugin 1.0.2.5
  stable/OBSPlugin/manifest.toml
Labels: size-small

#148 update STP
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#150 VFXEditor 1.7.9.2
  stable/VFXEditor/manifest.toml
Labels: size-large

#151 VFXEditor 1.7.9.2
  stable/VFXEditor/manifest.toml
Labels: version conflict, size-large

#152 VFXEditorCN 1.7.9.2
  stable/VFXEditorCN/images/icon.png
  stable/VFXEditorCN/manifest.toml
Labels: new plugin, size-large

#153 VFXEditor 1.7.9.0
  stable/VFXEditor/manifest.toml
Labels: version conflict, size-large

#154 SubmarineTracker CN
  stable/SubmarineTracker/manifest.toml
Labels: size-large

#155 VFXEditorCN 1.7.9.0
  stable/VFXEditorCN/manifest.toml
Labels: version conflict, size-large

#156 VFXEditorCN 1.7.9.0
  stable/VFXEditorCN/manifest.toml
Labels: size-small, version conflict

#157 VFXEditorCN 1.7.9.0
  stable/VFXEditorCN/manifest.toml
Labels: version conflict, size-large

#158 汉化RezPls 1.2.5.0
  stable/RezPls/manifest.toml
Labels: size-small, version conflict

#159 汉化 WaymarkPresetPlugin 1.4.7.0
  stable/WaymarkPresetPlugin/manifest.toml
Labels: version conflict, size-mid
