Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-12, with the labels that each got.

#169 [Testing] Currency Tracker 1.3.2.3
  testing/live/CurrencyTracker/manifest.toml
Labels: size-mid

#170 Currency Tracker 1.3.2.4
  stable/CurrencyTracker/images/icon.png
  stable/CurrencyTracker/manifest.toml
  testing/live/CurrencyTracker/manifest.toml
Labels: move channel, size-large

#171 Currency Tracker 1.3.2.5
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#173 DeepDungeonTracker 1.0.0.3
  stable/DeepDungeonTracker/manifest.toml
Labels: size-small, version conflict

#172 [Testing]Casexile 1.0.0.0
  testing/live/Casexile/manifest.toml
Labels: version conflict, size-mid

#175 Fix AdventurerInNeed Sig (1.3.0.2)
  stable/AdventurerInNeed/manifest.toml
Labels: size-small, version conflict
