Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-05, with the labels that each got.

#70 Update 3 CN plugins
  hold/stable/Visibility/manifest.toml
  hold/testing/Visibility/images/icon.png
  hold/testing/Visibility/manifest.toml
  stable/GatherBuddy/manifest.toml
  stable/SimpleTweaksPlugin/manifest.toml
  stable/Visibility/images/icon.png
  stable/Visibility/manifest.toml
Labels: new plugin, version conflict, size-mid

#71 STP 1.8.7.1
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#73 Update STP
  stable/SimpleTweaksPlugin/manifest.toml
Labels: version conflict, size-mid

#75 Update SLB
  stable/StarlightBreaker/manifest.toml
Labels: size-small

#74 [Stable] UsedName 0.8.2.2
  stable/UsedName/manifest.toml
Labels: size-small

#76 Update CharacterPanelRefined
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small, version conflict

#78 update PPI
  stable/PartyIcons/manifest.toml
Labels: size-small

#77 GoodMemory Api8
  stable/GoodMemory/manifest.toml
Labels: size-small

#79 XIVWindowResizer CN
  testing/live/XIVWindowResizer/manifest.toml
Labels: size-small

#80 DailyDutyCN
  stable/DailyDuty/manifest.toml
Labels: size-mid

#82 Accountant 1.3.5.1
  stable/Accountant/manifest.toml
Labels: size-small

#84 fix build error
  stable/DailyDuty/manifest.toml
Labels: size-mid

#86 NoTankYou CN
  stable/NoTankYou/manifest.toml
Labels: size-mid

#87 Update Distance&Ping
  stable/Distance/manifest.toml
  stable/PingPlugin/manifest.toml
Labels: size-small

#88 Update EngageTimer
  stable/EngageTimer/manifest.toml
Labels: size-small

#89 适配API8，添加汉化
  stable/BetterPartyFinder/manifest.toml
Labels: size-mid

#91 mp tick bar
  hold/stable/MPTickBar/manifest.toml
  stable/MPTickBar/images/icon.png
  stable/MPTickBar/images/image1.png
  stable/MPTickBar/manifest.toml
Labels: new plugin, size-mid

#92 EngageTimer
  stable/EngageTimer/manifest.toml
Labels: size-small

#93 [DailyDuty]更新至最新版本，修正翻译
  stable/DailyDuty/manifest.toml
Labels: size-small

#94 更新CharacterPanelRefined汉化和版本号
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#95 Adv in Need
  stable/AdventurerInNeed/manifest.toml
Labels: size-small, version conflict

#96 Fix AetherCompass
  testing/live/AetherCompass/manifest.toml
Labels: size-small

#98 [Stable] UsedName 0.8.2.3
  stable/UsedName/manifest.toml
Labels: size-small

#99 add new plugin PriceInsightCN
  stable/PriceInsightCN/images/icon.png
  stable/PriceInsightCN/images/imagecn.png
  stable/PriceInsightCN/manifest.toml
Labels: new plugin, size-mid

#100 [Testing] NoKillPlugin 1.0.8.0
  testing/live/NoKillPlugin/images/icon.png
  testing/live/NoKillPlugin/manifest.toml
Labels: size-small
