Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-11, with the labels that each got.

#160 [Testing] Currency Tracker 1.3.1.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-large

#163 [Testing] Currency Tracker 1.3.1.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small, version conflict

#164 BetterPlaytime 1.4.0.1
  stable/BetterPlaytime/manifest.toml
Labels: size-small, version conflict

#165 Hunty 1.2.1.1
  stable/Hunty/manifest.toml
Labels: version conflict, size-large

#166 LogogramHelper support zhcn
  testing/live/LogogramHelperCN/images/icon.png
  testing/live/LogogramHelperCN/manifest.toml
Labels: new plugin, size-large

#167 fix url broken
  stable/PriceInsightCN/manifest.toml
Labels: size-small
