Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-09, with the labels that each got.

#116 Update PriceInsightCN
  stable/PriceInsightCN/manifest.toml
Labels: size-small

#123 [Stable] UsedName 0.8.3.3
  stable/UsedName/manifest.toml
Labels: size-small

#125 更新CharacterPanelRefined
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#128 [Stable] RemotePartyFinder 1.0.11
  hold/stable/RemotePartyFinder/manifest.toml
  stable/RemotePartyFinder/images/icon.png
  stable/RemotePartyFinder/manifest.toml
Labels: new plugin, size-mid

#130 Fix 📏 CN 6.4
  stable/Distance/manifest.toml
Labels: size-small

#131 Update orch
  stable/orchestrion/manifest.toml
Labels: size-mid

#133 Update orch2
  stable/orchestrion/manifest.toml
Labels: size-small

#134 Update Vis
  stable/Visibility/manifest.toml
Labels: size-small

#135 Update stp
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#136 [Stable] UsedName 0.8.3.5
  stable/UsedName/manifest.toml
Labels: size-small

#137 [Testing] Currency Tracker 1.2.3.1
  testing/live/CurrencyTracker/manifest.toml
Labels: size-small

#138 ChatTwo 6.4
  stable/ChatTwo/images/icon.png
  stable/ChatTwo/manifest.toml
Labels: new plugin, size-large

#139 Chat2
  stable/ChatTwo/images/icon.png
  stable/ChatTwo/manifest.toml
Labels: new plugin, size-large

#141 SonarPlugin v0.5.4.1
  hold/stable/SonarPlugin/manifest.toml
  stable/SonarPlugin/images/icon.png
  stable/SonarPlugin/images/image1.png
  stable/SonarPlugin/images/image2.png
  stable/SonarPlugin/images/image3.png
  stable/SonarPlugin/images/image4.png
  stable/SonarPlugin/images/image5.png
  stable/SonarPlugin/images/logo.png
  stable/SonarPlugin/manifest.toml
Labels: new plugin, size-large

#143 [Testing] Better Targeting System 0.0.7.1
  testing/live/BetterTargetingSystem/manifest.toml
Labels: size-small
