Repository ottercorp/DalamudPluginsD17, pull requests merged in 2023-06, with the labels that each got.

#101 merge upstream
  stable/PriceInsightCN/manifest.toml
Labels: size-small

#103 STP update
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#104 PrefPro update
  stable/PrefPro/manifest.toml
Labels: size-small, version conflict

#105 [Stable] RemotePartyFinder 1.0.10
  stable/RemotePartyFinder/manifest.toml
Labels: size-mid

#107 [Better Party Finder]过滤功能增强
  stable/BetterPartyFinder/manifest.toml
Labels: size-mid
