Repository ottercorp/DalamudPluginsD17, pull requests merged in 2024-09, with the labels that each got.

#241 VFXEditorCN 忘了.是.哪个.版本
  stable/VFXEditorCN/manifest.toml
Labels: size-large

#242 SonarPlugin v0.6.6.1
  hold/stable/SonarPlugin/manifest.toml
  stable/SonarPlugin/images/icon.png
  stable/SonarPlugin/images/image1.png
  stable/SonarPlugin/images/image2.png
  stable/SonarPlugin/images/image3.png
  stable/SonarPlugin/images/image4.png
  stable/SonarPlugin/images/image5.png
  stable/SonarPlugin/images/logo.png
  stable/SonarPlugin/manifest.toml
Labels: size-large

#244 ARR
  stable/ARealmRecorded/manifest.toml
Labels: size-small, version conflict

#245 STP
  stable/SimpleTweaksPlugin/manifest.toml
Labels: version conflict, size-large

#246 Update GB
  stable/GatherBuddy/manifest.toml
Labels: size-small, version conflict

#247 Fancy loading Image
  stable/Dalamud.LoadingImage/manifest.toml
Labels: size-small

#248 orch
  hold/stable/orchestrion/manifest.toml
  stable/orchestrion/images/icon.png
  stable/orchestrion/manifest.toml
Labels: new plugin, size-large

#249 Update remote-party-finder
  stable/RemotePartyFinder/manifest.toml
Labels: version conflict, size-large

#250 Qol
  stable/QoLBar/images/icon.png
  stable/QoLBar/manifest.toml
Labels: new plugin, size-large

#251 Visibility
  stable/Visibility/manifest.toml
Labels: size-small, version conflict

#252 Orch
  stable/orchestrion/manifest.toml
Labels: size-small, version conflict

#253 XIVWindowResizer CN 7.0
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#255 CharacterPanelRefined本地化
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small, version conflict

#256 [Testing] UsedName v0.8.5.1
  stable/UsedName/manifest.toml
Labels: size-small

#257 add map images for CN7.0
  stable/HuntHelper/manifest.toml
Labels: size-small

#258 LogogramHelper本地化
  stable/LogogramHelper/manifest.toml
Labels: version conflict, size-large

#259 update StarlightBreaker 1.2.9.0
  stable/StarlightBreaker/manifest.toml
Labels: size-small

#260 OBSPlugin
  stable/OBSPlugin/images/icon.png
  stable/OBSPlugin/manifest.toml
Labels: new plugin, size-large

#261 Testing multihit
  testing/live/MultiHit/images/icon.png
  testing/live/MultiHit/manifest.toml
Labels: new plugin, size-large
