Repository ottercorp/DalamudPluginsD17, pull requests merged in 2024-10, with the labels that each got.

#266 refactor HHT1.0.0.25
  stable/HuntHelper/manifest.toml
Labels: size-small

#271 Ping Plugin for 7.0
  stable/PingPlugin/images/icon.png
  stable/PingPlugin/manifest.toml
Labels: new plugin, size-large

#272 Fix sig for submarine tracker
  hold/testing/live/SubmarineTracker/manifest.toml
  testing/live/SubmarineTracker/images/icon.png
  testing/live/SubmarineTracker/manifest.toml
Labels: move channel, size-large

#269 [Stable] PlayerTrack v3.4.8
  stable/PlayerTrack/manifest.toml
Labels: size-small

#274 STP
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-mid

#275 SonarPlugin v0.6.2.2
  stable/SonarPlugin/manifest.toml
Labels: size-small

#277 Update STP
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-small

#279 Umbra
  stable/Umbra/manifest.toml
Labels: size-mid

#280 Update manifest.toml
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#281 STP国服特供
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#283 [Testing] Multihit 0.0.2.1
  testing/live/MultiHit/manifest.toml
Labels: size-mid

#282 InventoryTools 同步上游更新
  stable/InventoryTools/manifest.toml
Labels: size-large

#285 [Testing] Update multihit to 0.0.2.2
  testing/live/MultiHit/manifest.toml
Labels: size-small

#284 Currency Tracker 1.4.5.0
  stable/CurrencyTracker/manifest.toml
Labels: size-small

#287 SonarPlugin v0.6.6.5
  stable/SonarPlugin/manifest.toml
Labels: size-small

#288 SonarPlugin v0.6.6.6
  stable/SonarPlugin/manifest.toml
Labels: size-small

#289 Distance CN 7.0
  stable/Distance/manifest.toml
Labels: size-small

#291 SonarPlugin v0.6.6.7
  stable/SonarPlugin/manifest.toml
Labels: size-small

#292 DI + orch
  stable/DamageInfoPlugin/manifest.toml
  stable/Umbra/manifest.toml
  stable/orchestrion/manifest.toml
Labels: size-large
