Repository ottercorp/DalamudPluginsD17, pull requests merged in 2024-03, with the labels that each got.

#182 STP test
  stable/SimpleTweaksPlugin/manifest.toml
  testing/live/SimpleTweaksPlugin/images/icon.png
  testing/live/SimpleTweaksPlugin/manifest.toml
  testing/live/Visibility/manifest.toml
Labels: move channel, size-large

#183 VFXEditorCN 1.8.2.4
  stable/VFXEditorCN/images/icon.png
  stable/VFXEditorCN/manifest.toml
Labels: new plugin, size-large

#186 汉化RezPls与WaymarkPresetPlugin
  stable/RezPls/manifest.toml
  stable/WaymarkPresetPlugin/manifest.toml
Labels: new plugin, size-large

#185 RemotePartyFinder 1.0.12
  stable/RemotePartyFinder/manifest.toml
Labels: size-large

#184 Update 5 plugins to CN 6.5
  stable/BetterPlaytime/manifest.toml
  stable/Mappy/manifest.toml
  stable/Weatherman/manifest.toml
  stable/XIVLogger/manifest.toml
  testing/live/Casexile/manifest.toml
Labels: size-small, version conflict

#194 Update ffxiv-priceinsight-cn for API 9
  stable/PriceInsightCN/images/icon.png
  stable/PriceInsightCN/images/imagecn.png
  stable/PriceInsightCN/manifest.toml
Labels: new plugin, size-large

#191 [API9] SonarPlugin v0.6.2.1
  stable/SonarPlugin/manifest.toml
Labels: size-small

#190 CharacterPanelRefined CN
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#193 为DelvUI添加ChnAxis
  stable/DelvUI/manifest.toml
Labels: size-small

#195 fix PriceinsightCN build error
  stable/PriceInsightCN/images/icon.png
  stable/PriceInsightCN/images/imagecn.png
  stable/PriceInsightCN/manifest.toml
Labels: new plugin, size-large

#196 XIVWindowResizer CN 6.5
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#197 Update PingPlugin
  stable/PingPlugin/manifest.toml
Labels: size-small

#199 Sync buildable plugins from goat
  pyckager/models.py
  stable/BetterMountRoulette/images/icon.png
  stable/BetterMountRoulette/manifest.toml
  stable/Craftimizer/manifest.toml
  stable/Dalamud.FindAnything/manifest.toml
  stable/ExtraChat/images/icon.png
  stable/ExtraChat/manifest.toml
  stable/NoSoliciting/images/icon.png
  stable/NoSoliciting/manifest.toml
  stable/OfDungeonsDeep/manifest.toml
  stable/OofPlugin/images/icon.png
  stable/OofPlugin/manifest.toml
  stable/PetRenamer/images/icon.png
  stable/PetRenamer/manifest.toml
  stable/PositionalGuide/manifest.toml
  stable/TitleRoulette/images/icon.png
  stable/TitleRoulette/manifest.toml
  stable/TrackyTrack/manifest.toml
  stable/VFXEditor/manifest.toml
  stable/Wholist/manifest.toml
  stable/XIVChat/images/icon.png
  stable/XIVChat/manifest.toml
  testing/live/PetScale/images/icon.png
  testing/live/PetScale/manifest.toml
  testing/live/PvpStats/images/icon.png
  testing/live/PvpStats/manifest.toml
  testing/live/TickTracker/manifest.toml
  testing/live/Visibility/images/icon.png
  testing/live/Visibility/manifest.toml
Labels: new plugin, move channel, size-large

#200 NoKillPlugin 1.1.0.0
  stable/NoKillPlugin/manifest.toml
Labels: size-small

#201 update StarlightBreaker
  stable/StarlightBreaker/images/icon.png
  stable/StarlightBreaker/manifest.toml
Labels: new plugin, size-large

#202 Fix Distance
  stable/Distance/manifest.toml
  testing/live/Distance/images/icon.png
  testing/live/Distance/images/image1.png
  testing/live/Distance/images/image2.png
  testing/live/Distance/manifest.toml
Labels: build failed

#206 汉化JobBars
  stable/JobBars/manifest.toml
Labels: size-mid

#207 Currency Tracker 1.3.4.5
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#208 PrefPro v1.2.1.2
  stable/PrefPro/manifest.toml
Labels: size-small

#209 Currency Tracker 1.3.4.7
  stable/CurrencyTracker/manifest.toml
Labels: size-mid

#210 DailyDuty NoTankYou 汉化
  stable/DailyDuty/manifest.toml
  stable/NoTankYou/manifest.toml
Labels: size-mid

#213 Eureka Helper 1.5.2.0
  stable/EurekaHelper/manifest.toml
Labels: size-small, version conflict

#215 BetterPartyFinder
  stable/BetterPartyFinder/manifest.toml
Labels: size-large

#216 Try fix pmb
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small

#217 Currency Tracker 1.3.5.0
  stable/CurrencyTracker/manifest.toml
Labels: size-large

#218 Fix PMB 2
  stable/MarketBoardPlugin/manifest.toml
Labels: size-small
