Repository ottercorp/DalamudPluginsD17, pull requests merged in 2024-04, with the labels that each got.

#219 DelvUI
  stable/DelvUI/manifest.toml
Labels: size-large

#220 TPie汉化
  stable/TPie/manifest.toml
Labels: size-small

#221 Sorta Kinda 1.0.4.8
  stable/SortaKinda/manifest.toml
Labels: size-small, version conflict

#222 PVP Tracker 0.2.3.2
  testing/live/PvpStats/manifest.toml
Labels: size-large

#223 Currency Tracker 1.3.5.1
  stable/CurrencyTracker/manifest.toml
Labels: size-small
