Repository ottercorp/DalamudPluginsD17, pull requests merged in 2025-09, with the labels that each got.

#370 XIVWindowResizer CN 7.3
  stable/XIVWindowResizer/manifest.toml
Labels: size-small

#377 SonarPlugin v0.7.3.9
  stable/SonarPlugin/manifest.toml
Labels: size-large

#380 AetherCompass 7.3
  testing/live/AetherCompass/manifest.toml
Labels: size-small

#382 STP CN 7.3
  stable/SimpleTweaksPlugin/manifest.toml
Labels: size-large

#383 FaderPlugin 7.3
  stable/FaderPlugin/manifest.toml
Labels: size-mid

#384 Fader plugin 7.3
  stable/FaderPlugin/manifest.toml
Labels: size-small

#385 VFXEditor cn 7.3
  stable/VFXEditor/manifest.toml
Labels: size-large

#389 ARR & GB 7.3
  stable/ARealmRecorded/manifest.toml
  stable/GatherBuddy/manifest.toml
Labels: size-small
