Repository ottercorp/DalamudPluginsD17, pull requests merged in 2025-08, with the labels that each got.

#359 RemotePartyFinder 1.0.17
  stable/RemotePartyFinder/manifest.toml
Labels: size-large

#360 ChatTwo
  stable/ChatTwo/manifest.toml
Labels: size-mid

#363 Update manifest.toml
  stable/QoLBar/manifest.toml
Labels: size-small

#364 ChatTwo 1.30.13
  stable/ChatTwo/manifest.toml
Labels: size-small
