Repository ottercorp/DalamudPluginsD17, pull requests merged in 2025-02, with the labels that each got.

#299 InventoryTools 国服 7.1 fixes
  stable/InventoryTools/manifest.toml
Labels: new plugin, size-large

#301 HuntHelper 1.0.0.27
  stable/HuntHelper/manifest.toml
Labels: size-small

#303 RemotePartyFinder 1.0.16
  stable/RemotePartyFinder/manifest.toml
Labels: size-large

#302 XIVWindowResizer CN 7.1
  stable/XIVWindowResizer/manifest.toml
Labels: size-small, version conflict

#304 umbra
  stable/Umbra/manifest.toml
  testing/live/Messenger/images/icon.png
  testing/live/ShowGear/images/icon.png
Labels: size-small, version conflict

#308 Fix distance 7.1
  stable/Distance/manifest.toml
Labels: size-small, version conflict

#312 StarlightBreaker 7.1
  stable/StarlightBreaker/images/icon.png
  stable/StarlightBreaker/manifest.toml
Labels: new plugin, size-large

#309 CharacterPanelRefined add zh-cn
  stable/CharacterPanelRefined/manifest.toml
Labels: size-small

#313 SonarPlugin v0.6.9.0
  stable/SonarPlugin/manifest.toml
Labels: size-large

#314 ChatTwo: Fix Chinese server list retrieval
  stable/ChatTwo/images/icon.png
  stable/ChatTwo/manifest.toml
Labels: size-small

#317 AdventurerInNeed CN 7.1
  stable/AdventurerInNeed/manifest.toml
Labels: size-small, version conflict

#318 Accountant CN API11 fixes.
  stable/Accountant/manifest.toml
Labels: size-small
